##### Import require dependencies

In [195]:
import torch
import math
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torchvision import datasets
from torchvision import transforms
from PIL import Image
import pandas as pd
import matplotlib.pyplot as plt
from torchinfo import summary

device = torch.accelerator.current_accelerator()
print(f"Torch version {torch.__version__} on {device}")

Torch version 2.7.0 on mps


##### How to use Tensor in PyTorch

In [159]:
# fix seed for random
torch.manual_seed(10)

# init matrix and get shape
a = torch.rand(4, 4)
print(a.shape)

# init matrix all ones or zeros
b = torch.ones(4, 4)
c = torch.randn(5, 4)

# random with normal distribution
mean = 5
std = 2
x = torch.randn(100) * std + mean

# broadcasting
rand = torch.rand(2, 4)
doubled = rand * (torch.arange(1, 5) * 2)

# math
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.linalg.svd(m3))       # singular value decomposition


torch.Size([4, 4])
Common functions:
tensor([[0.4800, 0.6964, 0.5396, 0.2496],
        [0.2677, 0.2380, 0.9126, 0.9748]])
tensor([[1., -0., 1., 1.],
        [1., -0., 1., 1.]])
tensor([[ 0., -1.,  0.,  0.],
        [ 0., -1.,  0.,  0.]])
tensor([[ 0.4800, -0.5000,  0.5000,  0.2496],
        [ 0.2677, -0.2380,  0.5000,  0.5000]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.4483, 0.3407],
        [0.5777, 0.8219]])
tensor([[1.3448, 1.0220],
        [1.7331, 2.4656]])
torch.return_types.linalg_svd(
U=tensor([[-0.4794, -0.8776],
        [-0.8776,  0.4794]]),
S=tensor([3.4253, 0.4509]),
Vh=tensor([[-0.6323, -0.7748],
        [

In [164]:
# use GPU with tensor
a = torch.rand(4, 4)
print(a)
a = a.to(device)
print(a)

# bridge with numpy
np_arr = np.random.rand(4, 5)
ts_arr = torch.from_numpy(np_arr)
print(ts_arr)

# convert to numpy
ts_arr = torch.rand(4, 5)
np_arr = ts_arr.numpy()
print(np_arr)

tensor([[0.7717, 0.6075, 0.5334, 0.7489],
        [0.0050, 0.7465, 0.6390, 0.6332],
        [0.3612, 0.6436, 0.6184, 0.0132],
        [0.2650, 0.7495, 0.1535, 0.3224]])
tensor([[0.7717, 0.6075, 0.5334, 0.7489],
        [0.0050, 0.7465, 0.6390, 0.6332],
        [0.3612, 0.6436, 0.6184, 0.0132],
        [0.2650, 0.7495, 0.1535, 0.3224]], device='mps:0')
tensor([[5.1130e-01, 7.1038e-01, 4.6547e-01, 5.1482e-01, 8.8741e-01],
        [4.2363e-01, 5.2895e-01, 7.3468e-01, 1.0377e-01, 3.2723e-01],
        [5.9653e-01, 4.8060e-02, 1.2806e-01, 8.6387e-01, 5.1738e-01],
        [4.2820e-01, 8.9939e-02, 2.1486e-01, 4.3624e-01, 6.4245e-04]],
       dtype=torch.float64)
[[0.7907677  0.756683   0.11291414 0.7221054  0.1384651 ]
 [0.9382006  0.4487694  0.56808156 0.6448014  0.11551696]
 [0.85658056 0.16931051 0.05397534 0.5941725  0.6413535 ]
 [0.8604609  0.09159291 0.39734888 0.89136016 0.76745033]]


##### Build Your First Multilayer Perceptron Model

In [15]:
!wget https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv

--2025-05-14 22:36:18--  https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23278 (23K) [text/plain]
Saving to: ‘pima-indians-diabetes.data.csv’

pima-indians-diabet 100%[===================>]  22.73K  --.-KB/s    in 0s      

2025-05-14 22:36:19 (47.5 MB/s) - ‘pima-indians-diabetes.data.csv’ saved [23278/23278]



In [173]:
data = pd.read_csv("./pima-indians-diabetes.data.csv")
print(f"Shape dataframe: {data.shape}")

Shape dataframe: (767, 9)


In [177]:
model = nn.Sequential(
    nn.Linear(8, 12),
    nn.ReLU(),
    nn.Linear(12, 8),
    nn.ReLU(),
    nn.Linear(8, 1),
    nn.Sigmoid()
)

summary(model, (8,))

Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [1]                       --
├─Linear: 1-1                            [12]                      108
├─ReLU: 1-2                              [12]                      --
├─Linear: 1-3                            [8]                       104
├─ReLU: 1-4                              [8]                       --
├─Linear: 1-5                            [1]                       9
├─Sigmoid: 1-6                           [1]                       --
Total params: 221
Trainable params: 221
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

##### Training a PyTorch Model

In [203]:
datasets = np.loadtxt("./pima-indians-diabetes.data.csv", delimiter=",")
X = datasets[:, :8]
y = datasets[:, 8]

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).reshape(-1, 1)

print(X.shape, y.shape)

# hyper parameters
loss_fn = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
n_epochs = 10
batch_size = 10

for epoch in range(n_epochs):
    print(f"Epoch {epoch}")
    count = 0
    for i in range(0, len(X), batch_size):
        Xbatch = X[i:i+batch_size]
        y_pred = model(Xbatch)
        ybatch = y[i:i+batch_size]
        loss = loss_fn(y_pred, ybatch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f'Finished epoch {epoch}, latest loss {loss}')

torch.Size([768, 8]) torch.Size([768, 1])
Epoch 0
Finished epoch 0, latest loss 0.5848190188407898
Epoch 1
Finished epoch 1, latest loss 0.5847914814949036
Epoch 2
Finished epoch 2, latest loss 0.5847690105438232
Epoch 3
Finished epoch 3, latest loss 0.5847495794296265
Epoch 4
Finished epoch 4, latest loss 0.5847325921058655
Epoch 5
Finished epoch 5, latest loss 0.5847175717353821
Epoch 6
Finished epoch 6, latest loss 0.5847043395042419
Epoch 7
Finished epoch 7, latest loss 0.5846925377845764
Epoch 8
Finished epoch 8, latest loss 0.5846821069717407
Epoch 9
Finished epoch 9, latest loss 0.5846728086471558
